import type { Metadata } from "next";
import { UserProvider } from "../context/UserContext";
import ".././styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-darkreader-mode="dynamic"
      data-darkreader-scheme="dark"
      data-darkreader-proxy-injected="true"
      data-darkreader-inline-stroke="ok"
      style={{ ["--darkreader-inline-stroke"]: "currentColor" } as React.CSSProperties}
    >
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
